// src/data.js
const employees = [
  {
    name: "Alice",
    surname: "Smith",
    age: 28,
    contract: "Full-time",
    availability: {
      Montag: "red",
      Dienstag: "red",
      Mittwoch: "green",
      Donnerstag: "red",
      Freitag: "green",
      Samstag: "grey",
      Sonntag: "grey",
    },
    ladenAufgemacht: 0,
    ladenAufmachen: false,
    ladenGeschlossen: 1,
    ladenSchliessen: true,
    transitAufgemacht: 0,
    transitAufmachen: false,
    transitGeschlossen: 4,
    transitSchliessen: true,
    pitstopAufgemacht: 5,
    pitstopAufmachen: true,
    pitstopGeschlossen: 0,
    pitstopSchliessen: false,
  },
  {
    name: "Bob",
    surname: "Johnson",
    age: 32,
    contract: "Part-time",
    availability: {
      Montag: "red",
      Dienstag: "red",
      Mittwoch: "red",
      Donnerstag: "grey",
      Freitag: "red",
      Samstag: "green",
      Sonntag: "grey",
    },
    ladenAufgemacht: 0,
    ladenAufmachen: false,
    ladenGeschlossen: 2,
    ladenSchliessen: true,
    transitAufgemacht: 3,
    transitAufmachen: true,
    transitGeschlossen: 0,
    transitSchliessen: false,
    pitstopAufgemacht: 0,
    pitstopAufmachen: false,
    pitstopGeschlossen: 4,
    pitstopSchliessen: true,
  },
  {
    name: "Charlie",
    surname: "Brown",
    age: 25,
    contract: "Full-time",
    availability: {
      Montag: "green",
      Dienstag: "red",
      Mittwoch: "green",
      Donnerstag: "green",
      Freitag: "red",
      Samstag: "green",
      Sonntag: "grey",
    },
    ladenAufgemacht: 0,
    ladenAufmachen: false,
    ladenGeschlossen: 3,
    ladenSchliessen: true,
    transitAufgemacht: 0,
    transitAufmachen: false,
    transitGeschlossen: 5,
    transitSchliessen: true,
    pitstopAufgemacht: 2,
    pitstopAufmachen: true,
    pitstopGeschlossen: 1,
    pitstopSchliessen: true,
  },
  {
    name: "David",
    surname: "Miller",
    age: 30,
    contract: "Full-time",
    availability: {
      Montag: "green",
      Dienstag: "green",
      Mittwoch: "green",
      Donnerstag: "grey",
      Freitag: "red",
      Samstag: "grey",
      Sonntag: "grey",
    },
    ladenAufgemacht: 3,
    ladenAufmachen: true,
    ladenGeschlossen: 4,
    ladenSchliessen: true,
    transitAufgemacht: 5,
    transitAufmachen: true,
    transitGeschlossen: 2,
    transitSchliessen: true,
    pitstopAufgemacht: 3,
    pitstopAufmachen: true,
    pitstopGeschlossen: 0,
    pitstopSchliessen: false,
  },
  {
    name: "Emma",
    surname: "Davis",
    age: 27,
    contract: "Part-time",
    availability: {
      Montag: "green",
      Dienstag: "red",
      Mittwoch: "green",
      Donnerstag: "grey",
      Freitag: "green",
      Samstag: "green",
      Sonntag: "grey",
    },
    ladenAufgemacht: 5,
    ladenAufmachen: true,
    ladenGeschlossen: 0,
    ladenSchliessen: false,
    transitAufgemacht: 0,
    transitAufmachen: false,
    transitGeschlossen: 3,
    transitSchliessen: true,
    pitstopAufgemacht: 4,
    pitstopAufmachen: true,
    pitstopGeschlossen: 2,
    pitstopSchliessen: true,
  },
  {
    name: "Frank",
    surname: "Wilson",
    age: 29,
    contract: "Full-time",
    availability: {
      Montag: "green",
      Dienstag: "green",
      Mittwoch: "red",
      Donnerstag: "grey",
      Freitag: "green",
      Samstag: "green",
      Sonntag: "grey",
    },
    ladenAufgemacht: 0,
    ladenAufmachen: false,
    ladenGeschlossen: 0,
    ladenSchliessen: false,
    transitAufgemacht: 0,
    transitAufmachen: false,
    transitGeschlossen: 1,
    transitSchliessen: true,
    pitstopAufgemacht: 0,
    pitstopAufmachen: false,
    pitstopGeschlossen: 3,
    pitstopSchliessen: true,
  },
  {
    name: "Grace",
    surname: "Anderson",
    age: 31,
    contract: "Full-time",
    availability: {
      Montag: "green",
      Dienstag: "red",
      Mittwoch: "green",
      Donnerstag: "green",
      Freitag: "green",
      Samstag: "red",
      Sonntag: "grey",
    },
    ladenAufgemacht: 0,
    ladenAufmachen: false,
    ladenGeschlossen: 5,
    ladenSchliessen: true,
    transitAufgemacht: 1,
    transitAufmachen: true,
    transitGeschlossen: 4,
    transitSchliessen: true,
    pitstopAufgemacht: 0,
    pitstopAufmachen: false,
    pitstopGeschlossen: 2,
    pitstopSchliessen: true,
  },
  {
    name: "Hannah",
    surname: "Martinez",
    age: 26,
    contract: "Part-time",
    availability: {
      Montag: "green",
      Dienstag: "green",
      Mittwoch: "red",
      Donnerstag: "red",
      Freitag: "green",
      Samstag: "green",
      Sonntag: "grey",
    },
    ladenAufgemacht: 0,
    ladenAufmachen: false,
    ladenGeschlossen: 1,
    ladenSchliessen: true,
    transitAufgemacht: 0,
    transitAufmachen: false,
    transitGeschlossen: 3,
    transitSchliessen: true,
    pitstopAufgemacht: 0,
    pitstopAufmachen: false,
    pitstopGeschlossen: 2,
    pitstopSchliessen: true,
  },
  {
    name: "Ian",
    surname: "Thompson",
    age: 33,
    contract: "Full-time",
    availability: {
      Montag: "grey",
      Dienstag: "grey",
      Mittwoch: "grey",
      Donnerstag: "grey",
      Freitag: "grey",
      Samstag: "grey",
      Sonntag: "grey",
    },
    ladenAufgemacht: 0,
    ladenAufmachen: false,
    ladenGeschlossen: 5,
    ladenSchliessen: true,
    transitAufgemacht: 4,
    transitAufmachen: true,
    transitGeschlossen: 1,
    transitSchliessen: true,
    pitstopAufgemacht: 3,
    pitstopAufmachen: true,
    pitstopGeschlossen: 0,
    pitstopSchliessen: false,
  },
  {
    name: "Jack",
    surname: "Davis",
    age: 27,
    contract: "Part-time",
    availability: {
      Montag: "green",
      Dienstag: "grey",
      Mittwoch: "green",
      Donnerstag: "grey",
      Freitag: "green",
      Samstag: "grey",
      Sonntag: "grey",
    },
    ladenAufgemacht: 0,
    ladenAufmachen: false,
    ladenGeschlossen: 0,
    ladenSchliessen: false,
    transitAufgemacht: 0,
    transitAufmachen: false,
    transitGeschlossen: 3,
    transitSchliessen: true,
    pitstopAufgemacht: 0,
    pitstopAufmachen: false,
    pitstopGeschlossen: 2,
    pitstopSchliessen: true,
  },
  {
    name: "Katie",
    surname: "Clark",
    age: 29,
    contract: "Full-time",
    availability: {
      Montag: "red",
      Dienstag: "red",
      Mittwoch: "red",
      Donnerstag: "red",
      Freitag: "red",
      Samstag: "red",
      Sonntag: "grey",
    },
    ladenAufgemacht: 0,
    ladenAufmachen: false,
    ladenGeschlossen: 0,
    ladenSchliessen: false,
    transitAufgemacht: 0,
    transitAufmachen: false,
    transitGeschlossen: 2,
    transitSchliessen: true,
    pitstopAufgemacht: 0,
    pitstopAufmachen: false,
    pitstopGeschlossen: 3,
    pitstopSchliessen: true,
  },
  {
    name: "Leo",
    surname: "White",
    age: 24,
    contract: "Full-time",
    availability: {
      Montag: "green",
      Dienstag: "green",
      Mittwoch: "green",
      Donnerstag: "green",
      Freitag: "green",
      Samstag: "green",
      Sonntag: "grey",
    },
    ladenAufgemacht: 0,
    ladenAufmachen: false,
    ladenGeschlossen: 1,
    ladenSchliessen: true,
    transitAufgemacht: 0,
    transitAufmachen: false,
    transitGeschlossen: 5,
    transitSchliessen: true,
    pitstopAufgemacht: 0,
    pitstopAufmachen: false,
    pitstopGeschlossen: 4,
    pitstopSchliessen: true,
  },
  {
    name: "Mia",
    surname: "Lee",
    age: 31,
    contract: "Full-time",
    availability: {
      Montag: "red",
      Dienstag: "green",
      Mittwoch: "red",
      Donnerstag: "green",
      Freitag: "red",
      Samstag: "green",
      Sonntag: "grey",
    },
    ladenAufgemacht: 0,
    ladenAufmachen: false,
    ladenGeschlossen: 2,
    ladenSchliessen: true,
    transitAufgemacht: 5,
    transitAufmachen: true,
    transitGeschlossen: 3,
    transitSchliessen: true,
    pitstopAufgemacht: 0,
    pitstopAufmachen: false,
    pitstopGeschlossen: 1,
    pitstopSchliessen: true,
  },
  {
    name: "Nathan",
    surname: "Evans",
    age: 28,
    contract: "Full-time",
    availability: {
      Montag: "green",
      Dienstag: "red",
      Mittwoch: "red",
      Donnerstag: "green",
      Freitag: "green",
      Samstag: "red",
      Sonntag: "grey",
    },
    ladenAufgemacht: 0,
    ladenAufmachen: false,
    ladenGeschlossen: 3,
    ladenSchliessen: true,
    transitAufgemacht: 0,
    transitAufmachen: false,
    transitGeschlossen: 4,
    transitSchliessen: true,
    pitstopAufgemacht: 5,
    pitstopAufmachen: true,
    pitstopGeschlossen: 0,
    pitstopSchliessen: false,
  },
  {
    name: "Olivia",
    surname: "Garcia",
    age: 30,
    contract: "Part-time",
    availability: {
      Montag: "green",
      Dienstag: "red",
      Mittwoch: "red",
      Donnerstag: "green",
      Freitag: "green",
      Samstag: "red",
      Sonntag: "grey",
    },
    ladenAufgemacht: 0,
    ladenAufmachen: false,
    ladenGeschlossen: 0,
    ladenSchliessen: false,
    transitAufgemacht: 4,
    transitAufmachen: true,
    transitGeschlossen: 1,
    transitSchliessen: true,
    pitstopAufgemacht: 5,
    pitstopAufmachen: true,
    pitstopGeschlossen: 0,
    pitstopSchliessen: false,
  },
];

export const ladenAufmachen = [
  {
    value: "ja",
    label: "kann Aufmachen",
  },
  {
    value: "nein",
    label: "kann nicht Aufmachen",
  },
];

// module.exports = { employees, statuses };
